# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5cb5d903e32b20b3b187ee57506936a6399cc336fbae0eb03c4ad09baf52be0c0a53860cca1472eaf51022c35ec878a8972f50823966026c0ef9d4e222f7251

test:
  secret_key_base: 2ab15b49997e6589a278d11d7db33a7b00ea11fec94c858cb32dbf083c77e94256c9808fabb46900bd663e5edcf6c891ecf967f241244e7c3fcf2a1da1b7e825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
